% snippet of code trying out best way of getting a smooth derivative
% (strain rate) from the 3D data

y=mean([x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment1;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment10;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment11;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment12;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment13;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment14;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment15;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment16;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment2;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment3;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment4;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment5;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment6;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment7;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment8;x_Strain_Longitudinal_Minimum_Ase15Model16SegmentZoningSegment9],1);
dy=gradient(y,dt);
dy_s=smoothdata(dy, 'sgolay',11);
plot(dy,'r')
